// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	helper "github.com/monitoror/monitoror/cli/helper"
	mock "github.com/stretchr/testify/mock"

	models "github.com/monitoror/monitoror/models"
)

// CLIPrinter is an autogenerated mock type for the CLIPrinter type
type CLIPrinter struct {
	mock.Mock
}

// PrintBanner provides a mock function with given fields:
func (_m *CLIPrinter) PrintBanner() {
	_m.Called()
}

// PrintDevMode provides a mock function with given fields:
func (_m *CLIPrinter) PrintDevMode() {
	_m.Called()
}

// PrintMonitorable provides a mock function with given fields: displayName, enabledVariants, erroredVariants
func (_m *CLIPrinter) PrintMonitorable(displayName string, enabledVariants []models.VariantName, erroredVariants []helper.ErroredVariant) {
	_m.Called(displayName, enabledVariants, erroredVariants)
}

// PrintMonitorableFooter provides a mock function with given fields: isProduction, nonEnabledMonitorableCount
func (_m *CLIPrinter) PrintMonitorableFooter(isProduction bool, nonEnabledMonitorableCount int) {
	_m.Called(isProduction, nonEnabledMonitorableCount)
}

// PrintMonitorableHeader provides a mock function with given fields:
func (_m *CLIPrinter) PrintMonitorableHeader() {
	_m.Called()
}

// PrintServerStartup provides a mock function with given fields: ip, port
func (_m *CLIPrinter) PrintServerStartup(ip string, port int) {
	_m.Called(ip, port)
}
